-- P1.01 — migration step 1 of Spec P3 §32: permission, role, role_permission, user, user_role.
-- Generated by `prisma migrate dev --create-only`, then HAND-EDITED (marked "HAND-EDIT").
--
-- One migration per migration-order STEP (P3 §32.1), not per table: the five tables of step 1 reference
-- each other (every audit column references user, and user references itself), so they are created
-- together. The user self-references are safe in one step because the bootstrap administrator row
-- (P3 §32.2) references its own id, which InnoDB accepts.

-- CreateTable
CREATE TABLE `permission` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `module` VARCHAR(40) NOT NULL,
    `action` VARCHAR(20) NOT NULL,
    `description` VARCHAR(500) NULL,

    UNIQUE INDEX `ux_permission_module_action`(`module`, `action`),
    PRIMARY KEY (`id`),
    -- HAND-EDIT: the closed action set (P3 §28.1, P6 §3.1), plus the four special actions P6 §10 and
    -- CN-01 name: accounting_period.reopen, receivable.write_off, device.register, device.revoke.
    CONSTRAINT `ck_permission_action` CHECK (`action` IN ('view', 'create', 'edit', 'delete', 'submit',
        'approve', 'reject', 'post', 'export', 'print', 'reopen', 'write_off', 'register', 'revoke')),
    CONSTRAINT `ck_permission_module` CHECK (REGEXP_LIKE(`module`, '^[a-z][a-z_]*$', 'c'))
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `role` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(20) NOT NULL,
    `name` VARCHAR(150) NOT NULL,
    `description` VARCHAR(500) NULL,
    `sort_order` INTEGER NOT NULL DEFAULT 0,
    `is_system` BOOLEAN NOT NULL DEFAULT false,
    `status` VARCHAR(30) NOT NULL DEFAULT 'active',
    `version` INTEGER NOT NULL DEFAULT 1,
    `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `created_by` BIGINT UNSIGNED NOT NULL,
    `updated_at` DATETIME(0) NULL,
    `updated_by` BIGINT UNSIGNED NULL,

    INDEX `ix_role_status`(`status`),
    INDEX `ix_role_created_by`(`created_by`),
    INDEX `ix_role_updated_by`(`updated_by`),
    UNIQUE INDEX `ux_role_code`(`code`),
    PRIMARY KEY (`id`),
    -- HAND-EDIT: enumerations and counters the database can guard.
    CONSTRAINT `ck_role_status` CHECK (`status` IN ('active', 'inactive')),
    CONSTRAINT `ck_role_version` CHECK (`version` >= 1),
    -- HAND-EDIT: a system row may be renamed but never deactivated (P3 §5.1, §31.3).
    CONSTRAINT `ck_role_system_active` CHECK (`is_system` = 0 OR `status` = 'active')
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `role_permission` (
    `role_id` BIGINT UNSIGNED NOT NULL,
    `permission_id` BIGINT UNSIGNED NOT NULL,

    INDEX `ix_role_permission_permission`(`permission_id`),
    PRIMARY KEY (`role_id`, `permission_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `person_id` BIGINT UNSIGNED NULL,
    `employment_profile_id` BIGINT UNSIGNED NULL,
    `username` VARCHAR(50) NOT NULL,
    `email` VARCHAR(254) NULL,
    `password_hash` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(20) NULL,
    `must_change_password` BOOLEAN NOT NULL DEFAULT false,
    `last_login_at` DATETIME(0) NULL,
    `failed_attempts` INTEGER NOT NULL DEFAULT 0,
    `locked_until` DATETIME(0) NULL,
    `two_factor_secret` VARCHAR(255) NULL,
    `two_factor_enabled` BOOLEAN NOT NULL DEFAULT false,
    `status` VARCHAR(30) NOT NULL DEFAULT 'active',
    `version` INTEGER NOT NULL DEFAULT 1,
    `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `created_by` BIGINT UNSIGNED NOT NULL,
    `updated_at` DATETIME(0) NULL,
    `updated_by` BIGINT UNSIGNED NULL,

    INDEX `ix_user_status`(`status`),
    INDEX `ix_user_person`(`person_id`),
    INDEX `ix_user_employment_profile`(`employment_profile_id`),
    INDEX `ix_user_created_by`(`created_by`),
    INDEX `ix_user_updated_by`(`updated_by`),
    UNIQUE INDEX `ux_user_username`(`username`),
    UNIQUE INDEX `ux_user_email`(`email`),
    PRIMARY KEY (`id`),
    -- HAND-EDIT: enumerations and counters the database can guard.
    CONSTRAINT `ck_user_status` CHECK (`status` IN ('active', 'disabled')),
    CONSTRAINT `ck_user_version` CHECK (`version` >= 1),
    CONSTRAINT `ck_user_failed_attempts` CHECK (`failed_attempts` >= 0)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user_role` (
    `user_id` BIGINT UNSIGNED NOT NULL,
    `role_id` BIGINT UNSIGNED NOT NULL,
    `granted_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `granted_by` BIGINT UNSIGNED NOT NULL,
    `expires_at` DATETIME(0) NULL,

    INDEX `ix_user_role_role`(`role_id`),
    INDEX `ix_user_role_granted_by`(`granted_by`),
    INDEX `ix_user_role_expires`(`expires_at`),
    PRIMARY KEY (`user_id`, `role_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `role` ADD CONSTRAINT `fk_role_created_by` FOREIGN KEY (`created_by`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `role` ADD CONSTRAINT `fk_role_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `role_permission` ADD CONSTRAINT `fk_role_permission_role` FOREIGN KEY (`role_id`) REFERENCES `role`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `role_permission` ADD CONSTRAINT `fk_role_permission_permission` FOREIGN KEY (`permission_id`) REFERENCES `permission`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `user` ADD CONSTRAINT `fk_user_created_by` FOREIGN KEY (`created_by`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `user` ADD CONSTRAINT `fk_user_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `user_role` ADD CONSTRAINT `fk_user_role_user` FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `user_role` ADD CONSTRAINT `fk_user_role_role` FOREIGN KEY (`role_id`) REFERENCES `role`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `user_role` ADD CONSTRAINT `fk_user_role_granted_by` FOREIGN KEY (`granted_by`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- HAND-EDIT: per-table rights for the app account (prisma/README.md). permission gets none: it is
-- system data written only by the seeder, so the running application cannot invent or alter a
-- permission (P6 §3.3). role_permission rows are replaced, never updated, so it gets DELETE only.
GRANT UPDATE, DELETE ON `role` TO 'rupai_app'@'%';
GRANT DELETE ON `role_permission` TO 'rupai_app'@'%';
GRANT UPDATE, DELETE ON `user` TO 'rupai_app'@'%';
GRANT UPDATE, DELETE ON `user_role` TO 'rupai_app'@'%';
