-- Generated by `prisma migrate dev --create-only`, then HAND-EDITED as the workflow requires.
-- The edits are marked "HAND-EDIT".

-- CreateTable
CREATE TABLE `probe_item` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(20) NOT NULL,
    `status` VARCHAR(30) NOT NULL,
    `gross_area` DECIMAL(14, 3) NOT NULL,
    `planted_area` DECIMAL(14, 3) NULL,
    -- HAND-EDIT: generated column implementing "one ACTIVE item per code" (Spec P2 §7.3 pattern).
    `active_key` VARCHAR(60) GENERATED ALWAYS AS (CASE WHEN `status` = 'active' THEN `code` ELSE NULL END) STORED,

    INDEX `ix_probe_item_code`(`code`),
    UNIQUE INDEX `ux_probe_item_active`(`active_key`),
    PRIMARY KEY (`id`),
    -- HAND-EDIT: CHECK constraint Prisma cannot express (Spec P3 §4.5 pattern).
    CONSTRAINT `ck_probe_item_planted_le_gross` CHECK (`planted_area` IS NULL OR `planted_area` <= `gross_area`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `probe_log` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `message` VARCHAR(200) NOT NULL,
    `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `probe_lookup` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(20) NOT NULL,
    `name` VARCHAR(150) NOT NULL,

    UNIQUE INDEX `ux_probe_lookup_code`(`code`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- HAND-EDIT: mutable tables get UPDATE/DELETE for the app account. probe_log gets none, so it is
-- append-only at the database level (Spec P3 §29, P14 §5.2).
GRANT UPDATE, DELETE ON `probe_item` TO 'rupai_app'@'%';
GRANT UPDATE, DELETE ON `probe_lookup` TO 'rupai_app'@'%';
